name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 1.0.0
homepage: https://github.com/ztalha6/google_maps_webservice

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.3.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^2.1.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  coverage: ^1.0.0
